on:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+.z"
  pull_request_target:
    branches:
      - "master"
      - "[0-9]+.[0-9]+.z"
  workflow_dispatch:
env:
  target_branch: ${{ github.base_ref || github.ref_name}}
jobs:
  copybara-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set target branch to ${{ env.target_branch }}
        run: |
          sed -e 's/SOT_BRANCH = "master"/SOT_BRANCH = "${{ env.target_branch }}"/' \
              -e 's/DESTINATION_BRANCH = "master"/DESTINATION_BRANCH = "${{ env.target_branch }}"/' \
              .github/workflows/copy.bara-os.sky.template > .github/workflows/copy.bara-os.sky
      - uses: ldziedziul/copybara-action@main
        name: Copybara ${{ env.target_branch }}
        with:
          ssh_key: ${{ secrets.GH_DEVOPSHAZELCAST_SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          copybara_options: "--nogit-destination-rebase"
          custom_config: copy.bara.sky
