on:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+.z"
  pull_request_target:
    branches:
      - "master"
      - "[0-9]+.[0-9]+.z"
  workflow_dispatch:
env:
  target_branch: ${{ github.base_ref || github.ref_name}}
jobs:
  copybara-os:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ldziedziul/copybara-action@main
        name: Copybara ${{ env.target_branch }}
        with:
          ssh_key: ${{ secrets.GH_DEVOPSHAZELCAST_SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: hazelcast/ldziedziul-test-mono
          sot_branch: ${{ env.target_branch }}
          destination_repo: hazelcast/ldziedziul-test-os
          copybara_options: "--nogit-destination-rebase"
          push_include: "os/** .github/workflows/copybara-os.yaml"
          pr_move: |
            ||os
            os/.github||.github
